### PR TITLE
first try adding new page for code of conduct

### PR DESCRIPTION
**Pull request by latompkins**
Hi Gordon,

I don't know how to build the site locally so I'm not sure if there are bugs in this, sorry about that! LMK if there is an easy way to build it locally and/or if there are problems with the commit!

cheers,
Lauren

### CODE REVIEW

**Comment by gordonwatts** [comment]
Building this site locally is a pain - the best I've seen is to use docker. But I can do this pretty easily now that I've figured out the magic behind it.

```
docker run --rm -it -v ${workspaceFolder}:/gitrepo -v ${workspaceFolder}/vendor/bundle:/usr/local/bundle -p 4001:4000 jekyll/jekyll:4.0 bash -c \"'cd /gitrepo; jekyll serve --incremental --force_poll'\"
```

Will cause it to be served at `http://localhost:4001/seattlesnowmass2021/` (in case you get brave and have docker running locally).

**Comment by gordonwatts** [comment]
After some minor edits, this is what it looks like:

image

**Comment by gordonwatts** [comment]
It occurs to me that zoom recordings usually expire. Perhaps we should contact YKKim to make sure this one does not - we want to keep it around for this.

**Comment by gordonwatts** [comment]
Ok - let me know if you are happy...

And - shoudl we be doing any sort of "post"/news item (see the one that current exists on the COVID in-person not in-person item): https://gordonwatts.github.io/seattlesnowmass2021/2020/09/01/COVID/

**Comment by latompkins** [comment]
Look good to me, thanks!  

I'm not sure it's necessary to do a "news" item as its going to be permanently on the top bar.

**Comment by gordonwatts** [comment]
Yes, it will be. Great! Going to merge! Thanks a lot for this!!

**Pull request merged**
